server:
  port: 10001


rocketmq:
  name-server: 10.206.148.44:9876
  producer:
    group: my-group
    send-message-timeout: 30000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-next-server: true
    retry-times-when-send-async-failed: 1
    retry-times-when-send-failed: 2
